# Generated by Django 2.2.3 on 2020-03-27 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NightlifePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('short_desc', models.CharField(max_length=200)),
                ('price_range', models.IntegerField()),
                ('liscenced', models.BooleanField()),
                ('street_num', models.IntegerField()),
                ('post_code', models.CharField(max_length=6)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.Culture')),
            ],
        ),
        migrations.CreateModel(
            name='LifestylePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('business', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('short_desc', models.CharField(max_length=200)),
                ('price_range', models.IntegerField()),
                ('street_num', models.IntegerField()),
                ('post_code', models.CharField(max_length=6)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.Culture')),
            ],
        ),
        migrations.CreateModel(
            name='FoodAndDrinkPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('short_desc', models.CharField(max_length=200)),
                ('vegan_option', models.BooleanField()),
                ('price_range', models.IntegerField()),
                ('street_num', models.IntegerField()),
                ('post_code', models.CharField(max_length=6)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.Culture')),
            ],
        ),
    ]
