# Generated by Django 2.2.3 on 2020-04-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightlifepage',
            name='business',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodanddrinkpage',
            name='price_range',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='foodanddrinkpage',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='foodanddrinkpage',
            name='vegan_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lifestylepage',
            name='business',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lifestylepage',
            name='price_range',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='lifestylepage',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='nightlifepage',
            name='liscenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nightlifepage',
            name='price_range',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='nightlifepage',
            name='short_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nightlifepage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
