# Generated by Django 2.2.3 on 2020-04-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodanddrinkpage',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.Culture'),
        ),
        migrations.AlterField(
            model_name='lifestylepage',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.Culture'),
        ),
        migrations.AlterField(
            model_name='nightlifepage',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.Culture'),
        ),
    ]
