# Generated by Django 2.2.3 on 2020-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20200402_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodanddrinkpage',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='lifestylepage',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='nightlifepage',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
